version: '3.7'
services:
  account_development:
    image: postgres:14
    # image: hartmutcouk/pg-repack-docker:1.4.6
    environment:
      POSTGRES_USER: ${ACCOUNT_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD}
      POSTGRES_HOST_ACCOUNT_METHOD: trust
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  account_test:
    image: postgres:14
    # image: hartmutcouk/pg-repack-docker:1.4.6
    environment:
      POSTGRES_USER: ${ACCOUNT_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD}
      POSTGRES_HOST_ACCOUNT_METHOD: trust
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  pgweb:
    image: sosedoff/pgweb
    container_name: "pgweb"
    ports:
      - "8081:8081"
