version: '3.7'
services:
  postgres:
    image: postgres:14
    # image: hartmutcouk/pg-repack-docker:1.4.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
